[project]
name = "pyrallel-consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cachetools>=7.0.0",
    "confluent-kafka>=2.13.0",
    "tenacity>=9.1.3",
]

[dependency-groups]
dev = [
    "bandit>=1.9.3",
    "pre-commit>=4.5.1",
    "pylint>=4.0.4",
]
