global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'pyrallel-consumer'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9091']
